Fix preview env

diff --git a/.github/workflows/preview.yml b/.github/workflows/preview.yml
--- a/.github/workflows/preview.yml
+++ b/.github/workflows/preview.yml
@@ -9,7 +9,7 @@ jobs:
         name: "Build and Deploy Preview Environment"
         runs-on: ubuntu-latest
         env:
-            TF_WORKSPACE: ${{ github.event.repository.name }}_${{ github.event.pull_request.number }}
+            WORKSPACE: ${{ github.event.repository.name }}_${{ github.event.pull_request.number }}
         defaults:
             run:
                 working-directory: .terraform/staging
@@ -21,16 +21,18 @@ jobs:
               uses: hashicorp/setup-terraform@v1
               with:
                   cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}
-            # Create terraform workspace
-            - name: Create terraform workspace
-              if: github.event_name == 'pull_request' && github.event.action != 'closed'
-              id: terraform-workspace-create
-              run: terraform workspace create ${TF_WORKSPACE} || echo "Workspace ${TF_WORKSPACE} already exists or cannot be created"
             # Initialize terraform
             - name: Initialize terraform
               if: github.event_name == 'pull_request' && github.event.action != 'closed'
               id: init-terraform
               run: terraform init
+            # Create terraform workspace
+            - name: Create terraform workspace
+              if: github.event_name == 'pull_request' && github.event.action != 'closed'
+              id: terraform-workspace-create
+              run: terraform workspace new ${WORKSPACE} || echo "Workspace ${WORKSPACE} already exists or cannot be created"
+            - name: Set workspace env
+              run: echo "TF_WORKSPACE=$(echo $WORKSPACE)" >> $GITHUB_ENV
             # Builds and deploys backend + Vercel preview environments
             - name: Build and deploy preview environment
               if: github.event_name == 'pull_request' && github.event.action != 'closed'
